### PR TITLE
Fix for mpv runtime and npm package stub

### PR DESCRIPTION
**Pull request by Kagami**
Continuing https://github.com/Kagami/mpv-promise/issues/1
Hi, here are the fixes for my workflow. `this` is `undefined` in case of ES Module.

Also added npm package stuff.
Please do `npm version minor && git push && git push --tags && npm publish` if you can.
Or I can publish to npm by myself if you don't want to deal with it.

### CODE REVIEW

**Comment by Kagami** [comment]
https://github.com/Kagami/mpv-promise/issues/1#issuecomment-1896295710
> Not sure I follow what you mean exactly

TypeScript transpiler created a very messy wrapper for `nopromise` CommonJS module when I imported it to ES module.  
However with `polyfill.js` submodule it's much better now, so I can live with it :)

> I'm OK if you push it

OK. Please tell me if you will need write access to that package at npm later.

**Comment by avih** [comment]
Thanks.

The change to `nopromise.js` re `setImmediate` is fine.

I wouldn't mind also replacing `this` with `Function("return this")()` at the init (the outer function call) if you think it's better.

How should `pollyfill.js` file be used?

For the readme, I'd prefer to keep it platform agnostic, so I'd be happier with some trivial instructions to (CommonJS) require the module normally (like the comment at `nopromise.js` shows), or simply to copy the file content verbatim into some other source file should also work to make `NoPromose` global, and then one can do `var Promise = NoPromise;` or some such, and maybe mention that it's compatible with browsers, including older IE, node, and other ES5 environments with `setTimeout`, such as mpv.

A generic example with typescript transpiling (not mpv-specific) would also be fine if you have such.

The rest of the readme seem to be mainly mpv-specific, and I think it fits better in mpv wiki or docs. This repo and nopromise are not mpv-specific.

The other files seem to be npm-specific, and I'd prefer to keep them out of this repo. I don't mind if your fork adds them for the sake of simpler publishing with npm. I also don't mind if the issue URL etc point to your fork.

The general gist of my preference is that your fork keeps `nopromise.js` itself in sync with this repo (we can improve it for things you think should be better), but I don't mind if your fork adds files to make it easier to publish to npm.

Also, while you're at it, would you mind adding the `.allSettled` static method (which was added in one of the recent commits) to the comment at the top?

**Comment by avih** [comment]
Also, unrelated, but I noticed that in one of your other repo (the typescript definitions?) you mentioned in a comment that mujs doesn't have DOM but does have `setTimeout`.

mujs doesn't have `setTimeout` because that's not part of ES5. It's part of the browser environment (as is the DOM).

But in mpv, because we have a-sync facilities at the libmpv API, we can implement `setTimeout`, `setInterval`, `require`, etc. All these are part of the mpv JS environment but provided by mpv and not by mujs.

For reference, they're implemented at https://github.com/mpv-player/mpv/blob/master/player/javascript/defaults.js

**Comment by Kagami** [comment]
> The rest of the readme seem to be mainly mpv-specific, and I think it fits better in mpv wiki or docs. This repo and nopromise are not mpv-specific.

Well, I put it in separate section. I just added stuff I needed for myself, I'm not currently in the mood of writing elaborate readme for IE and other cases, sorry :)

> The general gist of my preference is that your fork keeps nopromise.js itself in sync with this repo

OK, the only change necessary is the setImmediate fix, then I can just rebase on top of your commits, keeping the mpv-promise package...

> in mpv, because we have a-sync facilities at the libmpv API, we can implement setTimeout, setInterval, require, etc

Ah, thanks, I thought it comes from MuJS. I will update the comment later.

**Comment by Kagami** [comment]
So what do you think @avih? I can update PR and keep only fix to `nopromise.js`.

**Comment by avih** [comment]
Sorry about the delay. Been doing other things.

> I can update PR and keep only fix to `nopromise.js`.

Thanks, But no need for a PR just for this. I'll push this modification myself, hopefully soon, as well as updated README and a small improvements to `.finally`.

> How should `pollyfill.js` file be used?

You didn't reply to this. I don't mind including this or something similar if I understand how it works (and be not specific to mujs or mpv, as I think the prefix `mu` suggests?)

Also, since I haven't used nopromise as a pollyfill with typescript or other JS setups, would you mind also explaining the relation/usage with typescript, in node or other environments?

**Comment by Kagami** [comment]
> I'll push this modification myself, hopefully soon, as well as updated README and a small improvements to .finally.

Ok, thanks. I will close this one then.

> You didn't reply to this. I don't mind including this or something similar if I understand how it works (and be not specific to mujs or mpv, as I think the prefix mu suggests?)

Technically it's not necessary, just a convenient helper to put `Promise` into global scope, so that it can be used like a normal global builtin object.

If you import Promise from the module instead of putting it into global scope, VSCode shows the following error:

```ts
import Promise from "mpv-promise";

async function test() {
  return Promise.resolve("test");
}
```

```
Duplicate identifier 'Promise'.
Compiler reserves name 'Promise' in top level scope of a module containing async functions.
```

(Although TypeScript compiler is fine with that, so could be just issue with VSCode TypeScript extension, not sure.)
Also it's not convenient to import Promise every time you use async, you normally want to put polyfills into global scope once, at the start of the program.

And patching MuJS global scope is especially tricky because `this` could be undefined (e.g. in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#no_this_substitution); I've previously incorrectly said that it's solely caused by ES module) and MuJS doesn't provide global/globalThis/window global objects, that's why `var muGlobal = Function("return this")();` hack is required. (Actually it's pretty smart, I've found it [here](https://unpkg.com/@mpv-easy/tool@0.1.2/dist/global.js).)

> would you mind also explaining the relation/usage with typescript, in node or other environments?

So for async transpiling you need the Promise implementation (TypeScript generates FSM code which calls Promise inside, you can check e.g. [here](https://www.typescriptlang.org/play?target=1#code/IYZwngdgxgBAZgV2gFwJYHsI2QUxMgCgEoYBvAXwChRJZEUMtd8AmYsmYAd2FWWzyEiAbhjkgA)). So if the JS runtime doesn't implement Promise, you need to import some pure JS one instead. It doesn't necessary have to be global, it's just easier that way.

People usually just import bunch of core-js deps at the start of the program if they target some specific environment, which patches all corresponding global functions, and use them in the program as if they were available by default. Promise is no exception, same things applies to Map, Set, etc.

**Comment by Kagami** [comment]
> and be not specific to mujs or mpv, as I think the prefix mu suggests?

It's not specific, just a bit weird, because all modern browsers and node.js implement [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) or at least window/global. But not MuJS :)

The `Function` hack should also work everywhere. Except it may have problem with CSP's [unsafe-eval rule](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions).

**Comment by avih** [comment]
> Duplicate identifier 'Promise'.

Well, this is ES6 import, and I don't know how a CommonJS module should behave when included as ES6 import. But if you want to make it ES6-import compatible (as well), I wouldn't mind.

> And patching MuJS global scope is especially tricky because `this` could be undefined (e.g. in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#no_this_substitution);

Why are we talking about mujs in this repository? I don't mind the discussion, but I don't see the relvance.

If you're referring to the mpv env, then mpv documents exactly that `this` IS always defined, also in strict mode (in a module), because that's how I wrote it to behave, intentionally, and without contradition to the CommonJS `require` spec.

> It's not specific, just a bit weird, because all modern browsers and node.js implement [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) or at least window/global. But not MuJS :)

You keep forgetting that mujs is ES5.1. Read the spec. There's no `globalThis` in ES5.1, same as there isn't `setTimeout` or `require`. Anything beyond the pure language standard has to be added on top by whoever provides the environment.

Specifically for global, other than the common practice of using a Function constructor if it's really needed, the mpv JS docs do mention how a module can get the global object, or even how a script can add any variable it wants to be the global variable, as well as specific mention that the mpv environment is not a node replacement and is not supposed to run node modules.

Any script or module which tries to probe the global object will almost certainly get lost inan mpv env, because it's neither a browser nor node.

The mpv env is simply not designed to import node modules, because only node.js or clones/compatible envs can do that. Hopefully.

So again, remind me in simple terms why is mujs mentioned, and what's the problem with `globalThis` when talking about `nopromise`?

**Comment by Kagami** [comment]
> If you're referring to the mpv env, then mpv documents exactly that this IS always defined

It didn't work for me, that's why I made the fix.

> You keep forgetting that mujs is ES5.1

I didn't, I just said that's how you can do that in case of MuJS, because you can'd depend on `this` being global object.

> Why are we talking about mujs in this repository?

Because interpreter/environment specific fixes for a library is a normal thing?

> The mpv env is simply not designed to import node modules
> Any script or module which tries to probe the global object will almost certainly get lost inan mpv env

There's nothing very special about mpv environment. Imports work, most JS functions work. You can just detect if it's mpv inside a library and do the appropriate thing. People were writing isomorphic libraries (i.e. that work in both browser and node.js) for many years...

> So again, remind me in simple terms why is mujs mentioned, and what's the problem with globalThis when talking about nopromise?

I don't have any problems, mpv-promise works perfectly fine. I made this pull request because I thought you want your module to also work with mpv/typescript/esm setup (with the changes I provided), but at this point I have no idea what are we even talking about.

**Comment by avih** [comment]
> How should `pollyfill.js` file be used?

> Technically it's not necessary, just a convenient helper to put `Promise` into global scope, so that it can be used like a normal global builtin object.

I can read and understand what it does.

What I don't know is how a script uses it. Can you show a one-two-line script which uses `polyfill.js`? And in which environment is it supposed to be used? (node? browser? anything else?)

Does it only solve the problem that if nopromise.js is included (rather than imported) then it ends with `NoPromise` global property rather than `Promise`?

**Comment by Kagami** [comment]
> Can you show a one-two-line script which uses polyfill.js?

It's in the readme in this exact PR 😄

**Comment by avih** [comment]
> It didn't work for me, that's why I made the fix.

Well, before you workaround a bug you think exist, don't you think the bug (or incorrect docs, which is the same) should be reported so that maybe it can be fixed so that it doesn't need workarounds?

This belongs in mpv, but can you please share (here) a minimal mpv script or module which behaves in contradiction to the mpv documentation, with regards to `this` (or otherwise)?

That's the mpv docs:
> No global variable, but a module's this at its top lexical scope is the global object - also in strict mode. If you have a module which needs global as the global object, you could do this.global = this; before require.

For clarification, the docs intend to say that if you do `var foo = this;` as the first line of a script or a module (possibly after `"use strict";`), i.e. outside of any function - "top lexical scope" - then `foo` should be the global object.

Is this wrong?

**Comment by avih** [comment]
> It's in the readme in this exact PR 😄

Well, this is ES6/next `import`, which makes `Promise` a property of the global object. The spec of ES6 already includes `Promise` (and I don't know if it's modifiable - is it?), so isn't this contradition in terms? it requires ES6 to import a file which modifies the global `Promise` - which is part of the ES6 spec?

**Comment by Kagami** [comment]
> a minimal mpv script or module

```js
"use strict";
(function () {
  print("this2", typeof this);
})();
print("this1", typeof this);
```

```console
% mpv --force-window --idle=once --script=1.js
[1] this2 undefined
[1] this1 object
```

It's not contradiction to the docs, it's just the way ES modules are transpilled, in conjunction with strict mode. And no, I won't change the way it's transpilled :)

> it requires ES6 to import a file which modifies the global Promise - which is part of the ES6 spec?

No, this is perfectly fine to transpile only syntax and polyfill global objects separately. Even mpv docs mention that btw :)

**Comment by avih** [comment]
> ```
> % mpv --force-window --idle=once --script=1.js
> [1] this2 undefined
> [1] this1 object
> ```
>   
> It's not contradiction to the docs

Right, this is indeed exactly as documented, as expected, and as specified (ES5 and mpv docs): the 2nd ("top lexical scope") print of `this` is the global object, while inside that function, according to the spec, because this file is strict, `this` is undefined.

> it's just the way ES modules are transpilled

OK, I'm losing the plot.

Can we ignore everything above, and just tell me simply:
- Which problem or problems exactly does `polyfill.js` solve?

If one of those problems that `nopromise.js` doesn't always find the global object correctly, then can we fix this using a Function constructor at `nopromise.js`. so that what you want (`import "nopromise"`? or some other form?)?

Can you show me how?

I'm presuming the other problem it solves is that even if `nopromise.js` did find the global object correctly, then it still set `NoPromise` rather than `Promise`, right?

**Comment by Kagami** [comment]
> Which problem or problems exactly does polyfill.js solve?

No one! Just saves devs few lines of code. It's perfectly normal for npm packages to provide small helpful sub-modules so that devs don't have to type all the boilerplote code each time. But since you aren't planning to have npm module in your repo, you don't need that. (And even if you had, it's also not required, just helper module.)

> If one of those problems that nopromise.js doesn't always find the global object correctly

Yes, there's issue about `this.setImmediate` inside `nopromise.js`, but I fixed it with `typeof` check (not related to `polyfill.js` at all).

I think I understand now the source of confusion.
You don't need to use `this` to access `setImmediate` because it's global anyway. And you can check if it's missing with `typeof`.
On the other hand, if you want to put Promise into global scope, you need somehow get the global object. In MuJS, the best way is to use `Function` because `this` might be undefined (you can't always control that `this` is global object in your code).

But I can see you wanted G=global object in `nopromise.js`. Yeah, you can technically use `this || Function("return this")()` at the last line of `nopromise.js` instead, it should work too.

It just wasn't needed in my case (because I don't need `global.NoPromise`, I use ES modules), that's why I implemented check for `setImmediate` in a different way.

**Comment by Kagami** [comment]
> I'm presuming the other problem it solves is that even if nopromise.js did find the global object correctly, then it still set NoPromise rather than Promise, right?

In my case (ESM) `module.exports` is defined, so it doesn't even try to put it to global object. That's why I didn't touch that part of the code :)

And yeah, you want `Promise` on the global object too for a polyfill.

**Comment by avih** [comment]
> No one! Just saves devs few lines of code. It's perfectly normal for npm packages to provide small helpful sub-modules so that devs don't have to type all the boilerplote code each time

Sure. That's indeed useful.

So the problem it solves is to reduce the need for boilerplate so that `Promise` ends up as a property of the global object after e.g. `import "nopromise"` in ES6?

Would it be OK, for instance, if the instructions to make it a polyfill could be something like:
```js
require("nopromise").polyfill();
```

Then we can implement `polyfill` as a static method of `NoPromise` which would make `this` (i.e. the `NoPromise` object) the `Promise` property of the global object?

For instance (untested), if we added at `nopromise.js`:

```js
NoPromise.polyfill = function() {
    Function("return this")().Promise = this;
}
```

The goal, if possible, is that we (well, you, in the use case for npm) don't need `polyfill.js` (for the reason which it is there in the first place, eventhough not everyone needs it), by possibly enhancing `nopromise.js` to provide good enough functionality to replace it.

Is that possible?

If yes, what do you think is needed?

**Comment by Kagami** [comment]
> require("nopromise").polyfill();

Yeah, that can work too. I just prefer the submodule API a bit more (subjectively) and esbuild output for CommonJS-to-ESM wrapper is kinda huge if I import `nopromise` directly.

[esbuild-import-full-module.txt](https://github.com/avih/nopromise/files/14066332/esbuild-import-full-module.txt)
[esbuild-import-submodule.txt](https://github.com/avih/nopromise/files/14066333/esbuild-import-submodule.txt)

It's just easier to
```js
import "nopromise/polyfill";
```
than
```js
import NoPromise from "nopromise";
NoPromise.polyfill();
```

But I can keep `polyfill.js` in my fork, you don't need to add it.

**Comment by avih** [comment]
> I just prefer the submodule API a bit more (subjectively)

This is absolutely fine. If you think the submodule API is (for polyfill) is better, we'll go with that. I'm fine with it.

> and esbuild output for CommonJS-to-ESM wrapper is kinda huge if I import `nopromise` directly.

Not sure I follow. You mean that if you do
```
globalThis.Promise = require("nopromise")
```
then the wrapper ends up considerably bigger than if you add `polyfill.js` and then do
```js
import "nopromise/polyfill";
```

If yes, how is that so, when `polyfill.js` does exactly that anyway?

**Comment by avih** [comment]
> But I can keep `polyfill.js` in my fork,

The goal was to find something you're happy with instead of adding it in your fork. If you think this is the best approach then we can add it upstream (here).

I got no issue with that.

**Comment by Kagami** [comment]
> Not sure I follow. You mean that if you do

It's `import NoPromise from "nopromise"` vs `import "nopromise/polyfill"`. When you import something from CommonJS module in ES module esbuild adds special wrapper to the code (because those module APIs work differently). If you import just module (i.e. you need the side-effect of the import) then wrapper is very small. But it's minor issue to be honest :)

> If you think this is the best approach then we can add it upstream (here).

Well it's mostly useful as part of npm package. In your repo you just have bare module (nopromise.js). People nowadays import JS dependencies from npm, not vendor them.

**Comment by avih** [comment]
> `import NoPromise from "nopromise"`

But this is not the same as the polyfill anyway, because `Promise` would not be assigned, or am I wrong? So why are you comparing something which is useless as a polyfill, to the actual polyfill - which is useful as a polyfill?

Stay with me - let's focus only on the use case where `polyfill.js` is useful, even if we both know that it's not always useful, OK?

You also said you very much prefer the submodule API approach for polyfill, right? so if this is what you really want, there's nothing else which can replace `polyfill.js` because this is the only approach for submodule API, or am I wrong?

In this scenario, how does `import NoPromise from "nopromise"` replace the polyfill, functionality wise, regardless of the size of the wrapper?

> But it's minor issue to be honest :)

So help me out here. I admit I am not able to fully understand what ends up great and what not, and why, but I take your word.

Is there anything we can add to `nopromise.js` so that you/we don't need `polyill.js` but we're still happy?

Or are you only fully happy with having `polyfill.js`?

I'm OK with any reply, I just don't understand your preference completely.

**Comment by Kagami** [comment]
> because Promise would not be assigned, or am I wrong?

I meant if you later call `NoPromise.polyfill()`.

> so if this is what you really want, there's nothing else which can replace polyfill.js because this is the only approach for submodule API, or am I wrong?
> Or are you only fully happy with having polyfill.js?

Yeah.

**Comment by avih** [comment]
> > Or are you only fully happy with having polyfill.js?
> 
> Yeah.

OK.

Then in `polyfill.js`, would you be OK with `G` or `g` instead of `muGlobal` (this does not become a global property, right?)?

If yes, would you mind updating the PR to only keep the `nopromise.js` change for `setImmediate`, and `polyfill.js` with `g` var or some such? (without the readme, .npmignore, and the package json).

Also, in your repo, is there any reason to call it "mpv-promise" other than to make it easier to search "mpv" in the npm database?

Because it doesn't have anything mpv-specific, right? it basically only packages this repo as npm package...

**Comment by Kagami** [comment]
https://github.com/avih/nopromise/pull/2

**Comment by avih** [comment]
> `import NoPromise from "nopromise"`
> I meant if you later call `NoPromise.polyfill()`

But, if we would have used this `.polyfill`, then you would not need to import it first at all.

This line:
```js
require("nopromise").polyfill()
```

Is the complete replacement of
```js
import "nopromise/polyfill"
```

And there should be no difference in the wrapper size, because it's the exact code which `polyfill.js` uses anyway...

So I'm guessing that you insist, or prefer greatly, that `import` is used by users of this package, rather than requiring them to use CommonJS `require`?

And this is why you prefer the `polyfill.js` approach so strongly?

**Pull request closed without merging**
